### ISSUE TITLE
Feature in mixins declaring order

### ISSUE THREAD

**Issue by newsiberian** [vazco/meteor-universe-utilities-react#6]
Hello,
if you do the following:

```
mixins: [SubscriptionMixin, AutorunMixin],
```

all seems to work fine, but if you do:

```
mixins: [AutorunMixin, SubscriptionMixin],
```

then this.subscribe('something') can't find a collection.

**Comment by cristo-rabani** [comment]
Hello,
It's seems very strange, in next week we can check what's going on.
Thanks for reporting this.

**Comment by newsiberian** [comment]
Hi again, also I've failed to get results subscriptionReady with the "react-mixin" package with similar code:

```
@ReactMixin.decorate(AutorunMixin)
@ReactMixin.decorate(SubscriptionMixin)
export default class SomeClass extends React.Component {
```

or

```
@ReactMixin.decorate(SubscriptionMixin)
@ReactMixin.decorate(AutorunMixin)
export default class SomeClass extends React.Component {
```

there is no collections in "subscriptions" Object

Also, your README SubscriptionMixin example is confusing newbies like me:) Something like this works for me:

```
export default React.createClass({
  mixins: [SubscriptionMixin, AutorunMixin],
  getInitialState() {
    return {
      users: null,
      isSubscribed: false
    };
  },

  autorunUsers () {
    this.subscribe('users');
    if (this.subscriptionsReady()) {
      this.setState({
        users: Meteor.users.find().fetch(),
        isSubscribed: true
      });
    }
  },

  render () {
    if (!this.state.isSubscribed) {
      return (
        <p>Loading...</p>
      );
    }

    return (
      <ul>
        {this.state.users}
      </ul>
    );
  }
});
```

**Comment by radekmie** [comment]
Now `setState` is not necessary.

**Comment by newsiberian** [comment]
Hello, excuse me, but could you please roll back to 0.5.1. I've asked because using this method [**forceUpdate**] in SubscriptionMixin prevent me to get access to props changes in child components. Another words, using this mixin in Owner component blocks componentWillReceiveProps() and shouldComponentUpdate() normal working in **all** child components. Please, don't use it.

**Comment by radekmie** [comment]
New wersion with `setState`: https://github.com/vazco/meteor-universe-utilities-react/commit/ae770ec5bf541aa4d81ac0d6283f1dc8680ab455

**Comment by newsiberian** [comment]
@radekmie thank you for quick fix. Now it's work.
