### ISSUE TITLE
Does it maps require('react-addons-css-transition-group') as well?

### ISSUE THREAD

**Issue by veeramarni** [vazco/meteor-universe-utilities-react#7]
I'm using touchstonejs in app along with utilities-react. I'm able to work with UI components of touchstonejs individually. But when i include View, ViewManager, createApp components, i'm getting following error. Wondering if i need to do something similar for require('react-addons-css-transition-group') to map to available modules in meteor. 

```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

**Comment by cristo-rabani** [comment]
Hello,
Probably you have loaded two instances of React.
Do you use React from meteor package or from npm?
If you use React from meteor package and some of component are from npm.
(e.g by browserify)
So, in this situation you can try import them by universe:modules-npm
with configuration onto replacing React dependencies from npm package.
https://github.com/vazco/meteor-universe-modules-npm#replacing-requirements-of-npm-modules-to-system-js-modules

If you have react from npm and some components are provided from meteor packages you should check them if they don't have strong dependency to meteor package with React (like: React, react-runtime, jsx).
This package has that dependency.
So If this is your case, don't worry you can make own package with name react-runtime. This little hack will protect project from unwanted loading of react from meteor package.

**Comment by veeramarni** [comment]
I use `react` from meteor package. I was able to fix it by adding following. From 0.14 version of react, the addons can come as separate NPM packages, so inorder to use React.addons instead i made following changes and it works for me now. Let me know if this looks good or you have something better idea. Also, let me know if you want me to push my changes. 

```
System.registerDynamic('react-addons-css-transition-group', [], false, function (require, exports, module) {
    module.exports = Package['react-runtime'].React.addons.CSSTransitionGroup;
});
```

And then in package.npm.json as following

```
  "system": {
    // In bundle "react" will be replaced by universe:modules dependency.
    "dependencies": ["react", "react-dom", "react-addons-css-transition-group"]
  }
```

**Comment by cristo-rabani** [comment]
Hello, 

Good idea, you can make pull request with your solution.
